version: '3'

services:
  # db:
  postgres:
    image: betterblockchain/blockscout:pg-0.1.0
    restart: "no"
    expose:
      - "5432"

  # web ui:
  explorer:
    image: betterblockchain/blockscout:explorer-0.1.0
    restart: "no"
    tty: true
    environment:
      - DATABASE_URL=ecto://postgres:@postgres/explorer?ssl=false
      - ETHEREUM_JSONRPC_HTTP_URL=http://host.docker.internal:8545   # Here Set ETH HTTP
      - ETHEREUM_JSONRPC_WS_URL=ws://host.docker.internal:8546       # Here Set ETH WS
    ports:
      - "16001:4000"
    depends_on:
      - postgres
